preprocessing:
  dir_traindata: './data/train.csv'
  dir_testdata: './data/test.csv'
  random_seed : 2021
  classes: ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

output_dir: './submission/'