preprocessing:
  classes:
  - toxic
  - severe_toxic
  - obscene
  - threat
  - insult
  - identity_hate
  dir_testdata: ./data/test.csv
  dir_traindata: ./data/train.csv
  prep_method: nn_vectorization
  random_seed: 2021
output_dir: ./submission/
model_name: rnn
model_version: v2
nn_params:
  embedding_dim: 64
  epochs: 3
  sentence_maxlen: 200
  token_num_words: 5000
